//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reseon8Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.ucs.com/", ConfigurationName="Reseon8Service.MessageSenderWebService")]
    public interface MessageSenderWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ucs.com/MessageSenderWebService/getMessageIdRequest", ReplyAction="http://webservice.ucs.com/MessageSenderWebService/getMessageIdResponse")]
        System.Threading.Tasks.Task<Reseon8Service.getMessageIdResponse> getMessageIdAsync(Reseon8Service.getMessageIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ucs.com/MessageSenderWebService/sendMessageRequest", ReplyAction="http://webservice.ucs.com/MessageSenderWebService/sendMessageResponse")]
        System.Threading.Tasks.Task<Reseon8Service.sendMessageResponse> sendMessageAsync(Reseon8Service.sendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ucs.com/MessageSenderWebService/getErrorNumberRequest", ReplyAction="http://webservice.ucs.com/MessageSenderWebService/getErrorNumberResponse")]
        System.Threading.Tasks.Task<Reseon8Service.getErrorNumberResponse> getErrorNumberAsync(Reseon8Service.getErrorNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.ucs.com/MessageSenderWebService/sendTemplateMessageRequest", ReplyAction="http://webservice.ucs.com/MessageSenderWebService/sendTemplateMessageResponse")]
        System.Threading.Tasks.Task<Reseon8Service.sendTemplateMessageResponse> sendTemplateMessageAsync(Reseon8Service.sendTemplateMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageId", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.getMessageIdRequestBody Body;
        
        public getMessageIdRequest()
        {
        }
        
        public getMessageIdRequest(Reseon8Service.getMessageIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getMessageIdRequestBody
    {
        
        public getMessageIdRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageIdResponse", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.getMessageIdResponseBody Body;
        
        public getMessageIdResponse()
        {
        }
        
        public getMessageIdResponse(Reseon8Service.getMessageIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getMessageIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getMessageIdResponseBody()
        {
        }
        
        public getMessageIdResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessage", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.sendMessageRequestBody Body;
        
        public sendMessageRequest()
        {
        }
        
        public sendMessageRequest(Reseon8Service.sendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encoding;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string messageRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgHeader;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string encrypt;
        
        public sendMessageRequestBody()
        {
        }
        
        public sendMessageRequestBody(string senderName, string password, string messageBody, string encoding, string messageRecipients, string msgHeader, string campaignType, string encrypt)
        {
            this.senderName = senderName;
            this.password = password;
            this.messageBody = messageBody;
            this.encoding = encoding;
            this.messageRecipients = messageRecipients;
            this.msgHeader = msgHeader;
            this.campaignType = campaignType;
            this.encrypt = encrypt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendMessageResponse", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.sendMessageResponseBody Body;
        
        public sendMessageResponse()
        {
        }
        
        public sendMessageResponse(Reseon8Service.sendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendMessageResponseBody()
        {
        }
        
        public sendMessageResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getErrorNumber", WrapperNamespace="http://webservice.ucs.com/", IsWrapped=true)]
    public partial class getErrorNumberRequest
    {
        
        public getErrorNumberRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getErrorNumberResponse", WrapperNamespace="http://webservice.ucs.com/", IsWrapped=true)]
    public partial class getErrorNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public getErrorNumberResponse()
        {
        }
        
        public getErrorNumberResponse(long @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTemplateMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTemplateMessage", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.sendTemplateMessageRequestBody Body;
        
        public sendTemplateMessageRequest()
        {
        }
        
        public sendTemplateMessageRequest(Reseon8Service.sendTemplateMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendTemplateMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string senderName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string templateId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string encoding;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string messageRecipients;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgHeader;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string campaignType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string encrypt;
        
        public sendTemplateMessageRequestBody()
        {
        }
        
        public sendTemplateMessageRequestBody(string senderName, string password, string templateId, string encoding, string messageRecipients, string msgHeader, string parameters, string campaignType, string encrypt)
        {
            this.senderName = senderName;
            this.password = password;
            this.templateId = templateId;
            this.encoding = encoding;
            this.messageRecipients = messageRecipients;
            this.msgHeader = msgHeader;
            this.parameters = parameters;
            this.campaignType = campaignType;
            this.encrypt = encrypt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendTemplateMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendTemplateMessageResponse", Namespace="http://webservice.ucs.com/", Order=0)]
        public Reseon8Service.sendTemplateMessageResponseBody Body;
        
        public sendTemplateMessageResponse()
        {
        }
        
        public sendTemplateMessageResponse(Reseon8Service.sendTemplateMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sendTemplateMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sendTemplateMessageResponseBody()
        {
        }
        
        public sendTemplateMessageResponseBody(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface MessageSenderWebServiceChannel : Reseon8Service.MessageSenderWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class MessageSenderWebServiceClient : System.ServiceModel.ClientBase<Reseon8Service.MessageSenderWebService>, Reseon8Service.MessageSenderWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MessageSenderWebServiceClient() : 
                base(MessageSenderWebServiceClient.GetDefaultBinding(), MessageSenderWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MessageSenderWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageSenderWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MessageSenderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), MessageSenderWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageSenderWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MessageSenderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageSenderWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MessageSenderWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MessageSenderWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reseon8Service.getMessageIdResponse> Reseon8Service.MessageSenderWebService.getMessageIdAsync(Reseon8Service.getMessageIdRequest request)
        {
            return base.Channel.getMessageIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reseon8Service.getMessageIdResponse> getMessageIdAsync()
        {
            Reseon8Service.getMessageIdRequest inValue = new Reseon8Service.getMessageIdRequest();
            inValue.Body = new Reseon8Service.getMessageIdRequestBody();
            return ((Reseon8Service.MessageSenderWebService)(this)).getMessageIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reseon8Service.sendMessageResponse> Reseon8Service.MessageSenderWebService.sendMessageAsync(Reseon8Service.sendMessageRequest request)
        {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reseon8Service.sendMessageResponse> sendMessageAsync(string senderName, string password, string messageBody, string encoding, string messageRecipients, string msgHeader, string campaignType, string encrypt)
        {
            Reseon8Service.sendMessageRequest inValue = new Reseon8Service.sendMessageRequest();
            inValue.Body = new Reseon8Service.sendMessageRequestBody();
            inValue.Body.senderName = senderName;
            inValue.Body.password = password;
            inValue.Body.messageBody = messageBody;
            inValue.Body.encoding = encoding;
            inValue.Body.messageRecipients = messageRecipients;
            inValue.Body.msgHeader = msgHeader;
            inValue.Body.campaignType = campaignType;
            inValue.Body.encrypt = encrypt;
            return ((Reseon8Service.MessageSenderWebService)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reseon8Service.getErrorNumberResponse> Reseon8Service.MessageSenderWebService.getErrorNumberAsync(Reseon8Service.getErrorNumberRequest request)
        {
            return base.Channel.getErrorNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reseon8Service.getErrorNumberResponse> getErrorNumberAsync()
        {
            Reseon8Service.getErrorNumberRequest inValue = new Reseon8Service.getErrorNumberRequest();
            return ((Reseon8Service.MessageSenderWebService)(this)).getErrorNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Reseon8Service.sendTemplateMessageResponse> Reseon8Service.MessageSenderWebService.sendTemplateMessageAsync(Reseon8Service.sendTemplateMessageRequest request)
        {
            return base.Channel.sendTemplateMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Reseon8Service.sendTemplateMessageResponse> sendTemplateMessageAsync(string senderName, string password, string templateId, string encoding, string messageRecipients, string msgHeader, string parameters, string campaignType, string encrypt)
        {
            Reseon8Service.sendTemplateMessageRequest inValue = new Reseon8Service.sendTemplateMessageRequest();
            inValue.Body = new Reseon8Service.sendTemplateMessageRequestBody();
            inValue.Body.senderName = senderName;
            inValue.Body.password = password;
            inValue.Body.templateId = templateId;
            inValue.Body.encoding = encoding;
            inValue.Body.messageRecipients = messageRecipients;
            inValue.Body.msgHeader = msgHeader;
            inValue.Body.parameters = parameters;
            inValue.Body.campaignType = campaignType;
            inValue.Body.encrypt = encrypt;
            return ((Reseon8Service.MessageSenderWebService)(this)).sendTemplateMessageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageSenderWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MessageSenderWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://advwtsms01.adweag.local:8080/reson8fe/MessageSenderWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MessageSenderWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.MessageSenderWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MessageSenderWebServiceClient.GetEndpointAddress(EndpointConfiguration.MessageSenderWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            MessageSenderWebServicePort,
        }
    }
}
